spring:
  application:
    name: microservice-product
  data:
    mongodb:
      uri: mongodb://localhost:27017/productos
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka