server:
  port: 9090

spring:
  application:
    name: microservice-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/

