server:
  port: 8090

spring:
  application:
    name: microservice-eureka
  #luego borrar cuando lo tengas en config
  cloud:
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
